#!/bin/bash
# sweep_des_delays.sh - DES延迟参数扫描脚本
# 用法: ./scripts/sweep_des_delays.sh [参数名] [值列表...]
# 示例: ./scripts/sweep_des_delays.sh packet_transmission_delay 0.0001 0.0002 0.0005 0.001 0.002

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

# 默认实验参数
TEST_DURATION=${TEST_DURATION:-240}
TOPOLOGY=${TOPOLOGY:-fat-tree-k8-64}
TOR_ID=${TOR_ID:-41}
KEEP_AGG_ID=${KEEP_AGG_ID:-17}
TARGET_PREFIX=${TARGET_PREFIX:-192.168.41.0/24}
GLOBAL_CPUSET=${GLOBAL_CPUSET:-0-1}
DESD_CPUSET=${DESD_CPUSET:-0-1}

# 默认延迟配置（与 desd.c 中的默认值一致）
DEFAULT_PACKET_SEND_ENQUEUE_DELAY=0.002
DEFAULT_CONNECTION_DELAY=0.005
DEFAULT_CONNECTION_CLIENT_LEAD=0.001
DEFAULT_PACKET_TRANSMISSION_DELAY=0.02

# 配置文件路径
DELAY_CONFIG_FILE="$PROJECT_ROOT/desd_delays.conf"
SWEEP_RESULTS_DIR="$PROJECT_ROOT/results/sweep"

usage() {
    echo "用法: $0 <参数名> <值1> [值2] [值3] ..."
    echo ""
    echo "支持的参数名:"
    echo "  packet_send_enqueue_delay    - 发送事件入队延迟 (默认: $DEFAULT_PACKET_SEND_ENQUEUE_DELAY)"
    echo "  connection_delay             - 连接建立延迟 (默认: $DEFAULT_CONNECTION_DELAY)"
    echo "  connection_client_lead       - 客户端连接事件提前量 (默认: $DEFAULT_CONNECTION_CLIENT_LEAD)"
    echo "  packet_transmission_delay    - 数据包传输延迟 (默认: $DEFAULT_PACKET_TRANSMISSION_DELAY)"
    echo ""
    echo "环境变量:"
    echo "  TEST_DURATION   - 测试时长 (默认: 240)"
    echo "  TOPOLOGY        - 拓扑类型 (默认: fat-tree-k8-64)"
    echo "  TOR_ID          - ToR ID (默认: 41)"
    echo "  KEEP_AGG_ID     - 保留的 Agg ID (默认: 17)"
    echo "  TARGET_PREFIX   - 目标前缀 (默认: 192.168.41.0/24)"
    echo "  GLOBAL_CPUSET   - 全局 CPU 集 (默认: 0-1)"
    echo "  DESD_CPUSET     - DESD CPU 集 (默认: 0-1)"
    echo ""
    echo "示例:"
    echo "  $0 packet_transmission_delay 0.0001 0.0002 0.0005 0.001 0.002"
    echo "  $0 connection_delay 0 0.0001 0.0005 0.001"
    exit 1
}

# 检查参数
if [ $# -lt 2 ]; then
    usage
fi

PARAM_NAME="$1"
shift
PARAM_VALUES=("$@")

# 验证参数名
case "$PARAM_NAME" in
    packet_send_enqueue_delay|connection_delay|connection_client_lead|packet_transmission_delay)
        ;;
    *)
        echo "[ERROR] 未知参数名: $PARAM_NAME"
        usage
        ;;
esac

# 创建结果目录
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
SWEEP_RUN_DIR="$SWEEP_RESULTS_DIR/${PARAM_NAME}_${TIMESTAMP}"
mkdir -p "$SWEEP_RUN_DIR"

echo "=============================================="
echo " DES 延迟参数扫描"
echo "=============================================="
echo "参数名: $PARAM_NAME"
echo "扫描值: ${PARAM_VALUES[*]}"
echo "结果目录: $SWEEP_RUN_DIR"
echo "=============================================="

# 备份原始配置
cp "$DELAY_CONFIG_FILE" "$SWEEP_RUN_DIR/desd_delays.conf.backup"

# 生成配置文件的函数
generate_config() {
    local target_param="$1"
    local target_value="$2"
    
    local pse_delay="$DEFAULT_PACKET_SEND_ENQUEUE_DELAY"
    local conn_delay="$DEFAULT_CONNECTION_DELAY"
    local conn_lead="$DEFAULT_CONNECTION_CLIENT_LEAD"
    local trans_delay="$DEFAULT_PACKET_TRANSMISSION_DELAY"
    
    case "$target_param" in
        packet_send_enqueue_delay)
            pse_delay="$target_value"
            ;;
        connection_delay)
            conn_delay="$target_value"
            ;;
        connection_client_lead)
            conn_lead="$target_value"
            ;;
        packet_transmission_delay)
            trans_delay="$target_value"
            ;;
    esac
    
    cat > "$DELAY_CONFIG_FILE" <<EOF
# Auto-generated by sweep_des_delays.sh
# Sweep: $target_param = $target_value
packet_send_enqueue_delay=$pse_delay
connection_delay=$conn_delay
connection_client_lead=$conn_lead
packet_transmission_delay=$trans_delay
EOF
}

# 从 convergence_curve.csv 提取指标
extract_metrics() {
    local result_dir="$1"
    local curve_file="$result_dir/meta/convergence_curve.csv"
    local per_router_file="$result_dir/meta/per_router_convergence.csv"
    local t_fail_vt_file="$result_dir/meta/t_fail_vt.txt"
    
    if [ ! -f "$curve_file" ]; then
        echo "N/A,N/A,N/A,N/A,N/A"
        return
    fi
    
    # 提取 max convergence time (最后一行的第一列)
    local max_conv=$(tail -1 "$curve_file" | cut -d',' -f1)
    
    # 提取 t_fail_vt
    local t_fail_vt="N/A"
    if [ -f "$t_fail_vt_file" ]; then
        t_fail_vt=$(cat "$t_fail_vt_file")
    fi
    
    # 从 per_router_convergence.csv 计算 p50/p90/p99
    local p50="N/A"
    local p90="N/A"
    local p99="N/A"
    
    if [ -f "$per_router_file" ]; then
        # 跳过 header，提取 convergence_time_vt 列，排序后计算百分位
        local sorted_times=$(tail -n +2 "$per_router_file" | cut -d',' -f2 | sort -n)
        local count=$(echo "$sorted_times" | wc -l)
        
        if [ "$count" -gt 0 ]; then
            local p50_idx=$(echo "($count * 50 + 99) / 100" | bc)
            local p90_idx=$(echo "($count * 90 + 99) / 100" | bc)
            local p99_idx=$(echo "($count * 99 + 99) / 100" | bc)
            
            p50=$(echo "$sorted_times" | sed -n "${p50_idx}p")
            p90=$(echo "$sorted_times" | sed -n "${p90_idx}p")
            p99=$(echo "$sorted_times" | sed -n "${p99_idx}p")
        fi
    fi
    
    echo "$max_conv,$p50,$p90,$p99,$t_fail_vt"
}

# 初始化汇总文件
SUMMARY_FILE="$SWEEP_RUN_DIR/summary.csv"
echo "param_value,max_convergence,p50,p90,p99,t_fail_vt,result_dir" > "$SUMMARY_FILE"

# 重新编译 desd（确保使用最新代码）
echo ""
echo "[INFO] 重新编译 desd..."
make build/desd

# 扫描每个参数值
for i in "${!PARAM_VALUES[@]}"; do
    value="${PARAM_VALUES[$i]}"
    run_idx=$((i + 1))
    total_runs=${#PARAM_VALUES[@]}
    
    echo ""
    echo "=============================================="
    echo " 运行 $run_idx/$total_runs: $PARAM_NAME = $value"
    echo "=============================================="
    
    # 生成配置文件
    generate_config "$PARAM_NAME" "$value"
    echo "[INFO] 配置文件已更新:"
    cat "$DELAY_CONFIG_FILE"
    
    # 保存本次运行的配置
    cp "$DELAY_CONFIG_FILE" "$SWEEP_RUN_DIR/config_${value}.conf"
    
    # 运行实验
    echo ""
    echo "[INFO] 启动 DES 实验..."
    
    # 捕获实验结果目录
    RUN_OUTPUT=$(GLOBAL_CPUSET="$GLOBAL_CPUSET" DESD_CPUSET="$DESD_CPUSET" \
                 ./scripts/run_eye_catcher_des.sh "$TEST_DURATION" "$TOPOLOGY" "$TOR_ID" "$KEEP_AGG_ID" "$TARGET_PREFIX" 2>&1 | tee /dev/stderr)
    
    # 从输出中提取结果目录
    RESULT_DIR=$(echo "$RUN_OUTPUT" | grep -oP 'Result dir: \K[^\s]+' | tail -1)
    
    if [ -z "$RESULT_DIR" ] || [ ! -d "$RESULT_DIR" ]; then
        echo "[WARNING] 无法获取结果目录，尝试查找最新结果..."
        RESULT_DIR=$(ls -td "$PROJECT_ROOT/results/eye_catcher/des/${TOPOLOGY}_tor${TOR_ID}_"* 2>/dev/null | head -1)
    fi
    
    if [ -z "$RESULT_DIR" ] || [ ! -d "$RESULT_DIR" ]; then
        echo "[ERROR] 实验失败，无法找到结果目录"
        echo "$value,ERROR,ERROR,ERROR,ERROR,ERROR,N/A" >> "$SUMMARY_FILE"
        continue
    fi
    
    echo "[INFO] 结果目录: $RESULT_DIR"
    
    # 提取指标
    metrics=$(extract_metrics "$RESULT_DIR")
    echo "[INFO] 指标: max_conv,p50,p90,p99,t_fail_vt = $metrics"
    
    # 写入汇总
    echo "$value,$metrics,$RESULT_DIR" >> "$SUMMARY_FILE"
    
    # 创建软链接到 sweep 目录
    ln -sf "$RESULT_DIR" "$SWEEP_RUN_DIR/run_${value}"
    
    echo "[INFO] 运行 $run_idx/$total_runs 完成"
done

# 恢复原始配置
cp "$SWEEP_RUN_DIR/desd_delays.conf.backup" "$DELAY_CONFIG_FILE"

echo ""
echo "=============================================="
echo " 扫描完成"
echo "=============================================="
echo "汇总文件: $SUMMARY_FILE"
echo ""
echo "结果摘要:"
echo "-------------------------------------------"
column -t -s',' "$SUMMARY_FILE"
echo "-------------------------------------------"
echo ""
echo "可视化建议:"
echo "  python3 -c \"import pandas as pd; import matplotlib.pyplot as plt; df=pd.read_csv('$SUMMARY_FILE'); df.plot(x='param_value', y=['max_convergence','p50','p90','p99'], marker='o'); plt.xlabel('$PARAM_NAME'); plt.ylabel('Convergence Time (VT)'); plt.title('DES Delay Sweep: $PARAM_NAME'); plt.savefig('$SWEEP_RUN_DIR/sweep_plot.png'); print('Plot saved to $SWEEP_RUN_DIR/sweep_plot.png')\""
